name: "continuous-integration"
on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"

  pull_request:
    paths:
      - "src"
      - "tests"

jobs:
  validation:
    name: "Composer validation"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
          php-version: "${{ matrix.php-version }}"
          tools: composer

      - name: "Validate composer.json"
        run: "composer validate --strict"

  php-stan:
    name: "PHPStan Analyse"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
          php-version: "8.2"
          tools: composer

      - name: "Install PHPStan"
        run: "composer require --dev phpstan/phpstan"

      - name: "Run PHPStan"
        run: "vendor/bin/phpstan analyse src tests"

  php-cs-fixer:
    name: "PHP-CS-Fixer"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
          php-version: "8.2"
          tools: composer

      - name: "Install PHP-CS-Fixer"
        run: "composer require --dev friendsofphp/php-cs-fixer"

      - name: "Run PHP-CS-Fixer"
        run: "vendor/bin/php-cs-fixer fix --verbose --allow-risky=yes"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Fix styling
