name: "tests"

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"

  pull_request:
    paths:
      - "src"
      - "tests"

  workflow_dispatch:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

jobs:
  tests:
    name: "PHP Unit tests"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - php-version: "8.2"
            os: "ubuntu-latest"
            experimental: false
          - php-version: "8.3"
            os: "ubuntu-latest"
            experimental: false
          - php-version: "8.4"
            os: "ubuntu-latest"
            experimental: false
          - php-version: "latest"
            os: "ubuntu-latest"
            experimental: true
      fail-fast: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: "Install locked dependencies"
        if: "matrix.experimental == false"
        run: "composer config platform --unset && composer install ${{ env.COMPOSER_FLAGS }}"

      - name: "Install highest dependencies"
        if: "matrix.experimental == true"
        run: "composer config platform --unset && composer update ${{ env.COMPOSER_FLAGS }}"

      - name: "Prepare git environment"
        run: "git config --global user.name pusher && git config --global user.email pusher@example.com"

      - name: "Run PHPUnit tests"
        env:
          SECRET_URL: "${{secrets.SECRET_URL}}"
        run: |
          touch .env
          if [[ "${SECRET_URL}x" != "x" ]]; then
            wget -O .env ${SECRET_URL}
          fi

          source .env && vendor/bin/phpunit tests
